const progress_level=
[
    {level: "1", image: "a"},
    {level: "2", image: "b"},
    {level: "3", image: "c"},
    {level: "4", image: "d"},
    {level: "5", image: "e"},
    {level: "6", image: "f"},
    {level: "7", image: "g"},
    {level: "8", image: "h"},
    {level: "9", image: "i"},
    {level: "10", image: "j"},
    {level: "11", image: "k"},
    {level: "12", image: "l"},
    {level: "13", image: "m"},
    {level: "14", image: "n"},
    {level: "15", image: "o"},
    {level: "16", image: "p"},
    {level: "17", image: "q"},
    {level: "18", image: "r"},
    {level: "19", image: "s"},
    {level: "20", image: "t"},
    {level: "21", image: "u"},
    {level: "22", image: "v"},
    {level: "23", image: "w"},
    {level: "24", image: "x"},
    {level: "25", image: "y"},
    {level: "26", image: "z"},
]

